// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKEpbC7OxzWyFSkwAjT6Ue8RqisTN4WR8',
    appId: '1:728732933030:android:fd22e36a08e18b2a418d67',
    messagingSenderId: '728732933030',
    projectId: 'tangzo-apps',
    databaseURL: 'https://tangzo-apps-default-rtdb.firebaseio.com',
    storageBucket: 'tangzo-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_Z27vjO3P36Bm2JFZYfo1dXwamIMMGg',
    appId: '1:728732933030:ios:85500adff1c5c27f418d67',
    messagingSenderId: '728732933030',
    projectId: 'tangzo-apps',
    databaseURL: 'https://tangzo-apps-default-rtdb.firebaseio.com',
    storageBucket: 'tangzo-apps.firebasestorage.app',
    iosClientId: '728732933030-5ktikfai8crh9qjnld4cjr1bv2gat139.apps.googleusercontent.com',
    iosBundleId: 'com.tangzo.restaurant',
  );
}
